api_v3_store_search:
    path: /store/search
    defaults: { _controller: YilinkerCoreBundle:Api/StoreApi:searchStorename }

api_v3_store_search_auth:
    path: /auth/store/search
    defaults: { _controller: YilinkerCoreBundle:Api/StoreApi:searchStorename }
