fos_js_routing:
    routes_to_expose:
        - yilinker_backend_product_detail
        - yilinker_backend_transaction_cancel
        - yilinker_backend_transaction_order_details
        - yilinker_backend_transaction_order_product_detail_history
        - yilinker_backend_approve_deny_cancelled_transaction
        - yilinker_backend_order_product
        - yilinker_backend_seller_payout_proceed_payment
        - yilinker_backend_buyer_refund_proceed_refund
        - yilinker_backend_change_promo_status
        - yilinker_backend_delete_promo
        - yilinker_backend_check_promo_products
        - yilinker_backend_resolution_center_add_message
        - yilinker_backend_resolution_center_approve
        - yilinker_backend_resolution_center_reject
        - yilinker_backend_create_promo
        - yilinker_backend_update_promo
        - admin_accreditation_submit_remark
        - admin_accreditation_update_type
        - admin_user_detail
        - admin_seller_generate_referral_code
        - yilinker_backend_product_update_status
        - admin_account_register
        - admin_account_edit
        - admin_account_deactivate
        - admin_accreditation_download_legal_document
        - admin_accreditation_update_status
        - admin_add_user_bank
        - admin_edit_user_bank
        - admin_account_password_change
        - admin_voucher_edit
        - admin_generate_code
        - admin_update_manufacturer_unit_values
        - yilinker_backend_buyer_refund_order_product
        - yilinker_backend_manufacturer_payout_proceed_payment
        - cms_update_daily_login
        - admin_inhouse_form
        - core_widget_get_manufacturers
        - core_widget_get_brands
        - core_widget_get_product_categories
        - core_widget_upload_temp
        - backend_location_children
        - backend_store_address_validate
        - backend_user_address_submit
        - core_widget_upload_image
        - yilinker_backend_product_listings
        - yilinker_backend_batch_payout_create
        - yilinker_backend_batch_payout_update
        - yilinker_backend_batch_payout_detail_remove
        - yilinker_backend_batch_payout_head_remove
        - yilinker_backend_payout_batch_file_upload
        - yilinker_backend_payout_batch_file_download
        - yilinker_backend_payout_batch_file_remove
        - yilinker_backend_payout_batch_create_bulk
        - yilinker_backend_retrieve_payout_batch_detail
        - yilinker_backend_create_payout_batch_detail
        - yilinker_backend_get_payout_data
        - yilinker_backend_send_remarks
        - yilinker_core_shipping_category_search
        - yilinker_backend_product_update_shipping_category
        - yilinker_core_seller_store_search
        - yilinker_backend_buyer_refund_history_detail
        - yilinker_backend_buyer_refund_overview
        - cms_update_product_detail
        - cms_get_product_by_slug
        - backend_push_notification_create
        - backend_push_notification_update
        - frontend_search_product_route
        - frontend_product_route
        - frontend_search_seller_route
        - frontend_seller_route
        - cms_update_main_banner
        - cms_update_brand
        - cms_product_search_brand
        - cms_search_store
        - cms_update_seller
        - cms_render_store_list
        - cms_render_brand_list
        - cms_remove_brands
        - cms_remove_stores
        - cms_remove_products
        - cms_render_product_list
