dashboard_customized_category:
    path: /dashboard/customized-category
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:renderCustomizedCategory }

merchant_get_parent_categories:
    path: /category/getParentCategories
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:getParentCategories }
    methods: [GET]

merchant_get_custom_categories_hierarchy:
    path: /category/getCustomCategoriesHierarchy
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:getCustomCategoriesHierarchy }
    methods: [GET]

merchant_add_custom_categories:
    path: /category/addCustomCategory
    defaults: { _controller: YilinkerMerchantBundle:Api/CustomizedCategoryApi:addCustomCategory }
    methods: [POST]

merchant_update_custom_categories:
    path: /category/updateCustomCategories
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:updateCustomCategory }
    methods: [POST]

merchant_delete_custom_categories:
    path: /category/deleteCustomCategories
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:deleteCustomCategories }
    methods: [POST]

merchant_sort_custom_categories:
    path: /category/sortCustomCategories
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:sortCustomCategories }
    methods: [POST]

merchant_get_category_details:
    path: /category/getCategoryDetails
    defaults: { _controller: YilinkerMerchantBundle:CustomizedCategory:getCategoryDetailsAndParents }
    methods: [POST]
