fos_js_routing:
    routes_to_expose:
        - user_buyer_register
        - user_buyer_login
        - profile_info_update
        - profile_location_children
        - profile_create_address
        - profile_delete_address
        - profile_update_address
        - profile_change_email
        - profile_change_password
        - profile_update_contactnumber
        - transaction_cancellation
        - core_get_child_locations
        - core_get_active_conversation
        - core_get_conversation_messages
        - core_get_conversation_head
        - core_get_contacts
        - core_delete_conversation
        - core_send_message
        - core_upload_mutiple_message_image
        - core_set_conversation_as_read
        - checkout_buynow
        - user_follow
        - user_un_follow
        - core_upload_user_photo
        - core_verify_contact_number
        - core_user_disable_account
        - profile_resolution_center_add
        - profile_get_order_products
        - checkout_addresses
        - profile_messages
        - user_buyer_forgot_password_request
        - core_resend_sms_verification
        - core_resend_email_verification
        - api_checkout_update_contact_number
        - api_checkout_verify_mobile_code
        - api_checkout_resend_verification_code
        - core_sms_subscription
        - subscribe_email
        - core_user_create
        - user_register_success
        - core_address_default
        - subscribe_success
        - user_merge_social_media_send_notification
        - api_product_searchkeywords
        - checkout_validate_voucher
        - get_flash_sale_products
        - product_details
        - api_product_detail
        - get_store_webview
        - get_products_webview
        - core_forgot_password
        - user_reset_password_verification_code
        - core_send_token
        - profile_add_referrer_code
        - core_send_otp
        - core_validate_token
        - core_change_contact_number_request
        - api_product_list
