yilinker_oauth_server:
    resource: "@YilinkerOAuthServerBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secured/connect
    schemes:  [%protocol%]

yilinker_core:
    resource: "@YilinkerCoreBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [%protocol%]

fos_oauth_server_token:
    resource: "@YilinkerFrontendBundle/Resources/config/routing/oauth.yml"
    schemes:  [%protocol%]

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    schemes:  [%protocol%]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    schemes:  [%protocol%]

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
    schemes:  [%protocol%]

yilinker_frontend:
    resource: "@YilinkerFrontendBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [%protocol%]

nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    schemes:  [%protocol%]

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"