routes:
    
    # OAuth2 authorization endpoints for implicit/authorization grants        
    core_oauth_server_oauth_login:
        path: /oauth/v2/auth_login
        defaults: { _controller: YilinkerCoreBundle:Security:authorizeLogin }

    core_oauth_server_oauth_login_check:
        path: /oauth/v2/auth_login_check
        defaults: { _controller: YilinkerCoreBundle:Security:authorizeLoginCheck }
