fos_js_routing:
    routes_to_expose:
        - autocomplete_countries
        - home_page
        - core_get_child_cities
        - core_get_child_barangays
        - core_get_barangays_by_city
        - core_get_child_locations
        - core_address_add
        - core_address_edit
        - core_address_delete
        - core_address_default
        - core_address_get
        - core_change_password
        - core_change_email
        - core_change_contact_number
        - core_verify_contact_number
        - core_upload_user_photo
        - merchant_get_parent_categories
        - merchant_bank_account_add
        - merchant_bank_account_edit
        - merchant_bank_account_delete
        - merchant_bank_account_set_default
        - merchant_update_custom_categories
        - merchant_add_custom_categories
        - merchant_delete_custom_categories
        - merchant_sort_custom_categories
        - merchant_get_custom_categories_hierarchy
        - merchant_get_category_details
        - merchant_update_product_status
        - reseller_upload_product_list
        - user_update_info
        - transaction_cancellation
        - core_get_active_conversation
        - core_get_conversation_messages
        - core_get_conversation_head
        - core_get_contacts
        - reseller_upload_products
        - core_delete_conversation
        - core_send_message
        - core_upload_mutiple_message_image
        - core_set_conversation_as_read
        - user_share_via_email
        - reseller_view_product
        - merchant_bank_account_validate
        - merchant_bank_account_submit
        - merchant_accreditation
        - merchant_store_address_validate
        - merchant_location_children
        - merchant_accreditation_submit_business_information
        - dashboard_schedule_pickup
        - merchant_accreditation_submit_legal_documents
        - product_upload_edit_detail
        - product_upload_detail
        - product_search_child_category
        - product_search_category_attribute
        - product_upload_add_image
        - product_search_category
        - core_user_disable_account
        - dashboard_resolution_center_add
        - dashboard_get_order_products
        - dashboard_messages
        - product_upload_draft
        - user_forgot_password_request
        - core_resend_sms_verification
        - core_resend_email_verification
        - product_search_brand
        - core_sms_subscription
        - merchant_accreditation_submit_affiliate_legal_documents
        - user_merchant_registration
        - merchant_accreditation
        - user_store_information_submit_store_categories
        - user_affiliate_register
        - user_affiliate_forgot_password_request
        - user_affiliate_landing_page
        - user_affiliate_login
        - user_merchant_login
        - user_merchant_register
        - product_upload_get_child_category
        - product_upload_search_category
        - core_forgot_password
        - user_reset_password_verification_code
        - core_delivery_log
        - core_daterange_earnings
        - user_update_referrer
        - core_send_otp
        - core_user_create
        - core_send_token
        - dashboard_balance_withdrawal_bank_charge
        - core_change_contact_number_request
        - core_validate_token
        - bank_search_by_keyword
        - user_affiliate_default
        - user_affiliate_proccess_accreditation_information
        - user_store_information
        - merchant_user_warehouse_form
        - merchant_user_warehouse_delete
        - merchant_user_warehouse_inventory_update
        - dashboard_country_setup
        - translate_product
        - yilinker_core_shipping_category_search
        - product_translation
        - user_affiliate_proccess_legal_document
