yilinker_core:
    resource: "@YilinkerCoreBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [%protocol%]

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_oauth_server_token:
    resource: "@YilinkerMerchantBundle/Resources/config/routing/oauth.yml"
    schemes:  [%protocol%]

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    schemes:  [%protocol%]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    schemes:  [%protocol%]

EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
    schemes:  [%protocol%]

yilinker_merchant:
    resource: "@YilinkerMerchantBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [%protocol%]

nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    schemes:  [%protocol%]

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"