Yilinker\Bundle\CoreBundle\Entity\DisputeHistory:
    type: entity
    table: DisputeHistory
    indexes:
        dispute_history_dispute_status_type_id_user_order_dispute_status_type_status_type_id_idx:
            columns:
                - dispute_status_type_id
        dispute_history_dispute_id_dispute_dispute_id_idx:
            columns:
                - dispute_id
    id:
        disputeHistoryId:
            type: bigint
            column: dispute_history_id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateAdded:
            type: datetime
            column: date_added
    manyToOne:
        dispute:
            targetEntity: Dispute
            joinColumn:
                name: dispute_id
                referencedColumnName: dispute_id
            orphanRemoval: false
        disputeStatusType:
            targetEntity: DisputeStatusType
            joinColumn:
                name: dispute_status_type_id
                referencedColumnName: dispute_status_type_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
