Yilinker\Bundle\CoreBundle\Entity\InhouseProductUser:
    type: entity
    table: InhouseProductUser
    id:
        inhouseProductUserId:
            type: bigint
            id: true
            column: inhouse_product_user_id
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: smallint
            column: status
            options:
                default: '0'
        dateAdded:
            type: datetime
            column: date_added
        dateLastModified:
            type: datetime
            column: date_last_modified
    manyToOne:
        user:
            targetEntity: User
            inversedBy: inhouseProductUsers
            joinColumn:
                name: user_id
                referencedColumnName: user_id
            orphanRemoval: false
        product:
            targetEntity: Product
            inversedBy: inhouseProductUsers
            joinColumn:
                name: product_id
                referencedColumnName: product_id
            orphanRemoval: false