Yilinker\Bundle\CoreBundle\Entity\OneTimePassword:
    type: entity
    table: OneTimePassword
    repositoryClass: Yilinker\Bundle\CoreBundle\Repository\OneTimePasswordRepository
    indexes:
        fk_onetimepassword_userid_user_userid_idx:
            columns:
                - user_id
        fk_onetimepassword_countryid_country_countryid_idx:
            columns:
                - user_id
    id:
        oneTimePasswordId:
            type: integer
            id: true
            column: one_time_password_id
            generator:
                strategy: IDENTITY
    fields:
        contactNumber:
            type: string
            length: '255'
            column: contact_number
        token:
            type: string
            length: '255'
            column: token
        provider:
            type: integer
            column: provider
            options:
                default: '0'
        dateAdded:
            type: datetime
            column: date_added
        dateLastModified:
            type: datetime
            column: date_last_modified
        tokenExpiration:
            type: datetime
            column: token_expiration
        isActive:
            type: boolean
            column: is_active
            options:
                default: true
        tokenType:
            type: string
            length: '255'
            column: token_type
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: user_id
            orphanRemoval: false
            inversedBy: oneTimePasswords
        country:
            targetEntity: Country
            joinColumn:
                name: country_id
                referencedColumnName: country_id
            orphanRemoval: false
            inversedBy: oneTimePasswords
    lifecycleCallbacks: {  }
