Yilinker\Bundle\CoreBundle\Entity\OrderStatus:
    type: entity
    table: OrderStatus
    repositoryClass: Yilinker\Bundle\CoreBundle\Repository\OrderStatusRepository
    id:
        orderStatusId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: order_status_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
        description:
            type: string
            nullable: false
            length: 500
            fixed: false
    oneToMany:
        orderHistories:
            targetEntity: OrderHistory
            mappedBy: orderStatus
    lifecycleCallbacks: {  }