Yilinker\Bundle\CoreBundle\Entity\OrderProductStatus:
    type: entity
    table: OrderProductStatus
    id:
        orderProductStatusId:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: order_product_status_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        description:
            type: string
            nullable: false
            length: 500
            fixed: false
        class:
            type: string
            length: 100
            column: class
            options:
                 default: ''
    oneToMany:
        orderProducts:
            targetEntity: OrderProduct
            mappedBy: orderProductStatus
    lifecycleCallbacks: {  }
