Yilinker\Bundle\CoreBundle\Entity\OrderProductShipmentHistory:
    type: entity
    table: OrderProductShipmentHistory
    repositoryClass: Yilinker\Bundle\CoreBundle\Repository\OrderProductShipmentHistoryRepository
    id:
        orderProductShipmentHistoryId:
            type: bigint
            column: order_product_shipment_history_id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateAdded:
            type: datetime
            column: date_added

    manyToOne:
        orderProductShipment:
            targetEntity: OrderProductShipment
            joinColumn:
                name: order_product_shipment_id
                referencedColumnName: order_product_shipment_id
            orphanRemoval: false
        orderProductShipmentStatus:
            targetEntity: OrderProductShipmentStatus
            joinColumn:
                name: order_product_shipment_status_id
                referencedColumnName: order_product_shipment_status_id
            orphanRemoval: false
    indexes:
        fk_orderproductshipmenthistory_orderproductshipmentid_orderproductshipment_orderproductshipmentid_idx:
            columns:
                - order_product_shipment_id
        fk_orderproductshipmenthistory_orderproductshipmentstatusid_orderproductshipmentstatus_orderproductshipmentstatusid_idx:
            columns:
                - order_product_shipment_status_id
    lifecycleCallbacks: {  }
