Yilinker\Bundle\CoreBundle\Entity\OrderProduct:
    type: entity
    table: OrderProduct
    repositoryClass: Yilinker\Bundle\CoreBundle\Repository\OrderProductRepository
    indexes:
        fk_order_product_order_id_idx:
            columns:
                - order_id
        fk_order_product_order_product_status_id_idx:
            columns:
                - order_product_status_id
        fk_order_product_product_id_idx:
            columns:
                - product_id
        fk_order_product_seller_id_idx:
            columns:
                - seller_id
        fk_order_product_brand_id_idx:
            columns:
                - brand_id
        fk_order_product_product_category_id_idx:
            columns:
                - product_category_id
        fk_order_product_product_image_id_idx:
            columns:
                - product_image_id
        fk_order_product_condition_product_condition_productconditionid_idx:
            columns:
                - condition_id
    id:
        orderProductId:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            column: order_product_id
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
            nullable: false
            unsigned: false
        returnableQuantity:
            type: integer
            nullable: false
            unsigned: false
        totalPrice:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: total_price
        unitPrice:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: unit_price
        origPrice:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: orig_price
        productName:
            type: string
            nullable: false
            length: 1024
            fixed: false
            column: product_name
        paymentMethodCharge:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: payment_method_charge
        yilinkerCharge:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: yilinker_charge
        handlingFee:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: handling_fee
        shippingFee:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            column: shipping_fee
            options:
                default: 0.00
        additionalCost:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            options:
                default: '0'
            column: additional_cost
        net:
            type: decimal
            precision: 12
            scale: 4
            column: net
            nullable: true
        commission:
            type: decimal
            precision: 12
            scale: 4
            column: commission
            nullable: true
            options:
                default: '0'
        attributes:
            type: string
            nullable: false
            column: attributes
            length: 1024
        dateAdded:
            type: datetime
            nullable: false
            column: date_added
        lastDateModified:
            type: datetime
            nullable: false
            column: last_date_modified
        sku:	    
            type: string
            nullable: false
            column: sku
            options:
                default: ""
        weight:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            options:
                default: '0'
        length:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            options:
                default: '0'
        width:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            options:
                default: '0'
        height:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            options:
                default: '0'
        description:
            type: text
            nullable: true
        shortDescription:
            column: short_description
            length: 1024
            options:
                default: ''
        brandName:
            column: brand_name
            length: 255
            options:
                default: ''
        manufacturerProductReference:
            column: internal_product_reference
            length: 255
            options:
                default: ''
        isNotShippable:
            type: boolean
            column: is_not_shippable
            options:
                default: '0'
        dateWaybillRequested:
            type: datetime
            nullable: true
            column: date_waybill_requested
    manyToOne:
        order:
            targetEntity: UserOrder
            inversedBy: orderProducts
            cascade: ['persist']
            joinColumn:
                name: order_id
                referencedColumnName: order_id
            orphanRemoval: false
        orderProductStatus:
            targetEntity: OrderProductStatus
            inversedBy: orderProducts
            joinColumn:
                name: order_product_status_id
                referencedColumnName: order_product_status_id
            orphanRemoval: false
        product:
            targetEntity: Product
            inversedBy: orderProducts
            joinColumn:
                name: product_id
                referencedColumnName: product_id
            orphanRemoval: false
        seller:
            targetEntity: User
            joinColumn:
                name: seller_id
                referencedColumnName: user_id
            orphanRemoval: false
        brand:
            targetEntity: Brand
            joinColumn:
                name: brand_id
                referencedColumnName: brand_id
            orphanRemoval: false
        productCategory:
            targetEntity: ProductCategory
            joinColumn:
                name: product_category_id
                referencedColumnName: product_category_id
            orphanRemoval: false
        condition:
            targetEntity: ProductCondition
            joinColumn:
                name: condition_id
                referencedColumnName: product_condition_id
            orphanRemoval: false
        image:
            targetEntity: ProductImage
            joinColumn:
                name: product_image_id
                referencedColumnName: product_image_id
            orphanRemoval: false
        manufacturerProductUnit:
            targetEntity: ManufacturerProductUnit
            joinColumn:
                name: manufacturer_product_unit_id
                referencedColumnName: manufacturer_product_unit_id
            orphanRemoval: false
        userWarehouse:
            targetEntity: UserWarehouse
            joinColumn:
                name: user_warehouse_id
                referencedColumnName: user_warehouse_id
            orphanRemoval: false
    oneToMany:
        packageDetails:
            targetEntity: PackageDetail
            mappedBy: orderProduct
        orderProductHistories:
            targetEntity: OrderProductHistory
            mappedBy: orderProduct
        orderProductCancellationDetails:
            targetEntity: OrderProductCancellationDetail
            mappedBy: orderProduct
        productReviews:
            targetEntity: ProductReview
            mappedBy: orderProduct
        earningTransactions:
            targetEntity: EarningTransaction
            mappedBy: orderProduct
    lifecycleCallbacks: {  }
