Yilinker\Bundle\CoreBundle\Entity\UserPointDailyLogin:
    type: entity
    manyToOne:
        source:
            targetEntity: User
            joinColumn:
                name: table_id
                referencedColumnName: user_id
            orphanRemoval: false