Yilinker\Bundle\CoreBundle\Entity\UserPointPurchase:
    type: entity
    manyToOne:
        source:
            targetEntity: OrderProduct
            joinColumn:
                name: table_id
                referencedColumnName: order_product_id
            orphanRemoval: false