core_one_time_password:
    path: /one-time-password
    defaults: { _controller: YilinkerCoreBundle:OneTimePassword:index }

core_one_time_password_send_sms:
    path: /sendsms
    defaults: { _controller: YilinkerCoreBundle:OneTimePassword:send }
