tables:
    Product:
        fields:
            #name:
            #    editable: true
            #    label: Product Name
            #description:
            #    editable: true
            #    label: Product Description
            #shortDescription:
            #    editable: true
            #    label: Product Short Description