gcm_add_auth:
    path: /auth/device/addRegistrationId
    defaults: { _controller: YilinkerCoreBundle:Api/DeviceApi:addRegistrationId }
    methods: [POST]

gcm_add:
    path: /device/addRegistrationId
    defaults: { _controller: YilinkerCoreBundle:Api/DeviceApi:addRegistrationId }
    methods: [POST]

gcm_delete:
    path: /auth/device/deleteRegistrationId
    defaults: { _controller: YilinkerCoreBundle:Api/DeviceApi:deleteRegistrationId }
    methods: [POST]

gcm_unauth_delete:
    path: /device/deleteRegistrationId
    defaults: { _controller: YilinkerCoreBundle:Api/DeviceApi:deleteRegistrationId }
    methods: [POST]

gcm_update:
    path: /auth/device/updateRegistrationId
    defaults: { _controller: YilinkerCoreBundle:Api/DeviceApi:updateRegistrationId }
    methods: [POST]
